// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/12/10 23:55:41
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/hinano/workspace/talent-tuner/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hinano/workspace/talent-tuner/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hinano/workspace/talent-tuner/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hinano/workspace/talent-tuner/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hinano/workspace/talent-tuner/frontend/plugins/**/*.{js,ts,mjs}","/Users/hinano/workspace/talent-tuner/frontend/composables/**/*.{js,ts,mjs}","/Users/hinano/workspace/talent-tuner/frontend/utils/**/*.{js,ts,mjs}","/Users/hinano/workspace/talent-tuner/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hinano/workspace/talent-tuner/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/hinano/workspace/talent-tuner/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/hinano/workspace/talent-tuner/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;