// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/chat': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat').default>>>>
    }
    '/api/check-session': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/check-session').default>>>>
    }
    '/api/claudeApiClient': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/claudeApiClient').default>>>>
    }
    '/api/create-payment-intent': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/create-payment-intent').default>>>>
    }
    '/api/download-pdf': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/download-pdf').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_i18n/:hash/:locale/messages.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/i18n/dist/runtime/server/routes/messages').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/server/routes/_ipx').default>>>>
    }
  }
}
export {}